[build]
  # Since this is a static site, we don't need a build command
  publish = "."
  functions = "netlify/functions"

[build.environment]
  # Set Node version for any future needs
  NODE_VERSION = "18"

[functions]
  # Configure the Node.js runtime for functions
  node_bundler = "esbuild"
  external_node_modules = ["https"]

[[headers]]
  # Apply to all paths
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers to help with API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  # Redirect from other domains to the main domain
  from = "https://calculadora-tesouro.netlify.app/*"
  to = "https://tesouro.gabes.dev/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect from GitHub Pages to the main domain
  from = "https://gabesdev.github.io/calculadora-tesouro/*"
  to = "https://tesouro.gabes.dev/:splat"
  status = 301
  force = true

[[redirects]]
  # Handle SPA routing (if needed in the future)
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Enable form handling (if you add forms later)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true

# Custom headers for API endpoints (if you create any)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"